version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=expert
      - POSTGRES_PASSWORD=expert
      - POSTGRES_DB=movie_expert
    ports:
      - '3535:5432'
    volumes: 
      - ./sql/database.sql:/docker-entrypoint-initdb.d/1.sql
volumes:
  db:
    driver: local